[develop]
script_dir=$base/lib/er_navigation

[install]
install_scripts=$base/lib/er_navigation

[options]
install_requires=
    setuptools
packages=find:

[options.entry_points]
console_scripts=
    gps_waypoint_controller = er_navigation.gps_waypoint_controller:main

[tool:pytest]
testpaths = test
