[metadata]
name = earth-rovers-sdk
version = 0.0.0
description = Earth Rovers SDK ROS2 Python nodes (bridge)

[develop]
script_dir=$base/lib/earth_rovers_sdk

[install]
install_scripts=$base/lib/earth_rovers_sdk

[options]
packages = find:
install_requires =
    requests
    websocket-client
    opencv-python

[options.entry_points]
console_scripts =
    earth_rover_bridge = earth_rovers_sdk.bridge_node:main
    bridge_node = earth_rovers_sdk.bridge_node:main
